[project]
name = "aihoteladvisor"
version = "0.1.0"
description = "aihoteladvisor"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "crewai>=0.95.0",
    "crewai-tools>=0.32.1",
]
